import React from 'react';

const Footer = ({ onChange }) => {
  return ( 
    <footer id='Footer'>
      <nav id='footer-navigation'>
        <div>
          <a href="#top">top</a>
        </div>
        <div>
          <select id='style-selector' onChange={onChange} >
            <option value="light">delta-lite</option>
            <option value="dark">delta-dark</option>
            <option value="geo">one-point-oh</option>
            <option value="mania">true-american</option>
          </select>
        </div>
      </nav>
      <div>
        <span>arnest00 &copy; 2021</span>
        <br />
        <span>All deltaChannel posts are owned and generated by its users.</span>
      </div>
    </footer>
  );
};
 
export default Footer;