import React from 'react';

const Footer = ({ themes, onChange }) => {
  const formatThemes = themes => {
    return themes.map((t, idx) => (
      <option key={idx} value={t.themeShort}>{t.themeLong}</option>
    ));
  };

  return ( 
    <footer className='Footer'>
      <nav className='footer-navigation'>
        <div>
          <a href="#top">top</a>
        </div>
        <div>
          <label>
            Theme:
            <select className='style-selector' onChange={onChange} defaultValue='' >
              <option value='' disabled>--Select theme--</option>
              {formatThemes(themes)}
            </select>
          </label>
        </div>
      </nav>
      <div className='footer-disclaimer'>
        <span>arnest00 &copy; 2021</span>
        <br />
        <span>All deltaChannel posts are owned and generated by its users.</span>
      </div>
    </footer>
  );
};
 
export default Footer;