const Footer = () => {
  return ( 
    <footer id='Footer'>
      <span>arnest00 &copy; 2021</span>
      <br />
      <span>deltaChannel is not affiliated with other text- or imageboards.</span>
      <br />
      <span>All posts are not owned or generated by deltaChannel, but its users.</span>
    </footer>
  );
};
 
export default Footer;